### ISSUE TITLE
Validation scripts don't detect cell lines

### ISSUE THREAD

**Issue by levitsky** [bigbio/proteomics-metadata-standard#330]
The validation scripts automatically select the template for validation based on the organisms listed. For this reason, "cell line" annotations are not detected as such, see e.g. #329.

The script needs to be fixed to correctly detect cell lines. (I can't self-assign the issue but I'll fix the script myself.)

**Comment by ypriverol** [comment]
This issue has been fixed.

**Comment by levitsky** [comment]
It has? I didn't do anything about it and the validation script hasn't changed in 12 days. I think the issue has been worked around in pending submissions, but not fixed.
